version: '3.8'

networks:
  sim-iku-net:
    external: true
    name: sim-iku-net

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sim-iku-backend
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - sim-iku-net
    restart: unless-stopped
